quartz:
  enabled: true
server:
  port: 9090
spring:
  application:
    name: Spring-Quartz-Scheduler                                       #Quartz调度中心
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.20.247:3306/qrtz
    username: qrtz
    password: qrtz
    tomcat:
      initialSize: 20
      maxActive: 100
      maxIdle: 100
      minIdle: 20
      maxWait: 10000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  quartz:
    # 数据库方式
    job-store-type: jdbc
